t = 0;
dt = 0.001;
ks = 0.5;
kv = 0.4;
t_f = 12.565*ks/kv;
x = 0;
y = 0;
theta = 0;
figure(1);
myPlot = plot(x,y, 'b-');
xlim([-0.5, 0.5]);
ylim([-0.5, 0.5]);
%fx = zeros(1,ceil((t_f-t)/dt));
%fy = zeros(1,ceil((t_f-t)/dt));
index = 2;
while(t < t_f)
    vr = 1000*(0.3*kv + 0.14125*kv/ks*sin(t*kv/(2*ks)));
    vl = 1000*(0.3*kv - 0.14125*kv/ks*sin(t*kv/(2*ks)));
    w = (vr - vl) / 235;
    V = (vr + vl) / 2;
    theta = theta + w*dt/2;
    x = x + V*cos(theta)*dt;
    y = y + V*sin(theta)*dt;
    theta = theta + w*dt/2;
    set(myPlot, 'xdata', [get(myPlot, 'xdata') x/1000], 'ydata', [get(myPlot, 'ydata'), y/1000]);
    pause(0.0001);
    %fx(index) = x;
    %fy(index) = y;
    index = index+1;
    t = t + dt;
end
axis equal;
% plot(fx, fy);